export default () => ({
  items: [],
  manageMenu: [],
  userMenu: [],
  accountMenu: [],
  buyerMenu: [],
  sellerMenu: [],
  globalMenu: [],
  manageNavBar: [],
  sellerNavBar: [],
  locales: ['en-GB', 'fr'],
  fallbackLocale: 'en-GB',
  settings: {},
  defaultSettings: {},
})
