export const icons = {
  heart: 'mdi-heart-outline',
  localisation: 'mdi-map-marker-outline',
  help: 'mdi-help-circle-outline',
  padlock: 'mdi-lock',
  eye: 'mdi-eye-outline',
  credit_card: 'mdi-credit-card-multiple-outline',
  plus: 'mdi-plus',
  document: 'mdi-file-document-multiple-outline',
  trash: 'mdi-delete',
  clock: 'mdi-clock-time-four-outline',
  writing: 'mdi-pencil-box-multiple-outline',
  validate: 'mdi-check',
  shop: 'mdi-basket-outline',
  truck: 'mdi-truck-fast-outline',
  calendar: 'mdi-calendar-month-outline',
  search: 'mdi-magnify',
  network: 'mdi-wan',
  account: 'mdi-account-circle-outline',
  social: 'mdi-account-group-outline',
  preference: 'mdi-tune-vertical-variant',
  mail: 'mdi-email-outline',
  logout: 'mdi-logout-variant',
  choice: 'mdi-apps',
  left_arrow: 'mdi-chevron-left',
  menu_burger: 'mdi-menu',
  close: 'mdi-close',
  menu_point: 'mdi-dots-horizontal',
  home: 'mdi-home-outline',
  bank: 'mdi-bank-outline',
  star: 'mdi-star-outline',
  numero: 'mdi-numeric-1-circle-outline',
  check_circle: 'mdi-check-circle-outline',
  switch: 'mdi-toggle-switch',
  order: 'mdi-inbox-arrow-down-outline',
  settings: 'mdi-cog'
}
export const defaultIcon = 'mdi-plus'

export const iconsNames = Object.keys(icons)
