name: Unit tests

on:
  pull_request:
    branches: [ dev-flas ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install yarn
      run: yarn
    - name: Install vuex
      run: yarn add vuex
    - name: Run tests
      run: yarn jest
