name: Unit tests

on:
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: pnpm install --shamefully-hoist
      - name: Run tests
        run: pnpm test
